### PR TITLE
New quickstart guide

### PR DESCRIPTION
**Pull request by EkaanshArora**

### CODE REVIEW

**Comment by LichKing-2234** [comment]
why delete `MainActivity.java` and `MainApplication.java`? I can't run android now

**Comment by EkaanshArora** [comment]
Sorry about that, I have added the missing android files.
I have also added back the old Chinese readme, but that needs to be updated for the new app. Please help me update it as I don't know Chinese.

**Comment by LichKing-2234** [comment]
1、add `tools:replace="android:allowBackup"` to the application tag in AndroidManifest.xml
2、run `react-native unlink react-native-agora`
3、all the video is full screen in `ScrollView`, so I thought the remote video has some error when I run the demo first

**Comment by EkaanshArora** [comment]
I've made the requested changes

1、Added `tools:replace="android:allowBackup"` and `xmlns:tools="http://schemas.android.com/tools"` to the AndroidManifest
2、Unlinked `react-native-agora`
3、Reduced the height of the local video view to leave space for the remote feed to appear without scrolling, is this okay?

**Comment by EkaanshArora** [comment]
As requested I have removed the ScrollView and divided the screen to support upto four users.

**Pull request merged**
